name: AvaloniaExtensions CI build pipeline

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest

    steps:
      # Build
      - name: Clone avalonia-extensions
        uses: actions/checkout@v3
      - name: Setup dotnet sdk
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore backend dependencies
        run: dotnet restore
      - name: Build backend
        run: dotnet build --configuration Release --no-restore
