name: AvaloniaExtensions release pipeline

on:
  push:
    tags: [ v* ]

jobs:
  publish:

    name: Publish
    runs-on: ubuntu-latest

    steps:
      # Build
      - name: Clone avalonia-extensions
        uses: actions/checkout@v3
      - name: Setup dotnet sdk
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore backend dependencies
        run: dotnet restore
      - name: Build backend
        run: dotnet build --configuration Release --no-restore

      # Extract version number (v1.2.3) from the tag (refs/tags/v1.2.3)
      - name: Extract version number
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Create NuGet package (without the v version prefix)
      - name: Create AvaloniaExtensions package
        run: >
          dotnet pack
          --configuration Release
          --no-restore
          -p:PackageVersion=${RELEASE_VERSION:1}
          AvaloniaExtensions/AvaloniaExtensions.csproj

      # Upload the NuGet package
      - name: Upload release to NuGet
        run: >
          dotnet nuget push **/*.nupkg
          --source https://api.nuget.org/v3/index.json
          -k ${{ secrets.NUGET_API_KEY }}
          --skip-duplicate
